id: P37F1E12B
initial_creation_type: input
source_metadata:
  title: Dzogchen Pema Rigdzin Series
  language: bo
  description: Texts by Dzogchen Pema Rigdzin (rdzogs chen padma rig 'dzin, 1625–1697),
    the great adept who founded Dzogchen Monastery in Kham.
  volume:
    45a4d165f7ce4fb894435835ead8a7ec:
      title: A Dzogchen Tögal Prayer
      parent: Prayers
created_at: '2022-02-28T23:11:42.477343'
last_modified_at: '2022-02-28T23:11:42.477346'
statistics:
  total_words: 271
  total_non_words: 12
quality:
  non_words_ratio: 0.04
